/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as CatalogRouteImport } from './routes/catalog'
import { Route as AboutCompanyRouteImport } from './routes/about/company'
import { Route as AboutMentorRouteImport } from './routes/about/mentor'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as AuthenticatedPlatformIndexRouteImport } from './routes/_authenticated/platform/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutCompanyRoute = AboutCompanyRouteImport.update({
  id: '/about/company',
  path: '/about/company',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutMentorRoute = AboutMentorRouteImport.update({
  id: '/about/mentor',
  path: '/about/mentor',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPlatformIndexRoute =
  AuthenticatedPlatformIndexRouteImport.update({
    id: '/platform/',
    path: '/platform/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/catalog': typeof CatalogRoute
  '/about/company': typeof AboutCompanyRoute
  '/about/mentor': typeof AboutMentorRoute
  '/auth/': typeof AuthIndexRoute
  '/platform/': typeof AuthenticatedPlatformIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/catalog': typeof CatalogRoute
  '/about/company': typeof AboutCompanyRoute
  '/about/mentor': typeof AboutMentorRoute
  '/auth': typeof AuthIndexRoute
  '/platform': typeof AuthenticatedPlatformIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/catalog': typeof CatalogRoute
  '/about/company': typeof AboutCompanyRoute
  '/about/mentor': typeof AboutMentorRoute
  '/auth/': typeof AuthIndexRoute
  '/_authenticated/platform/': typeof AuthenticatedPlatformIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/catalog'
    | '/about/company'
    | '/about/mentor'
    | '/auth/'
    | '/platform/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/catalog'
    | '/about/company'
    | '/about/mentor'
    | '/auth'
    | '/platform'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/catalog'
    | '/about/company'
    | '/about/mentor'
    | '/auth/'
    | '/_authenticated/platform/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  CatalogRoute: typeof CatalogRoute
  AboutCompanyRoute: typeof AboutCompanyRoute
  AboutMentorRoute: typeof AboutMentorRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/company': {
      id: '/about/company'
      path: '/about/company'
      fullPath: '/about/company'
      preLoaderRoute: typeof AboutCompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/mentor': {
      id: '/about/mentor'
      path: '/about/mentor'
      fullPath: '/about/mentor'
      preLoaderRoute: typeof AboutMentorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/platform/': {
      id: '/_authenticated/platform/'
      path: '/platform'
      fullPath: '/platform/'
      preLoaderRoute: typeof AuthenticatedPlatformIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedPlatformIndexRoute: typeof AuthenticatedPlatformIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedPlatformIndexRoute: AuthenticatedPlatformIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  CatalogRoute: CatalogRoute,
  AboutCompanyRoute: AboutCompanyRoute,
  AboutMentorRoute: AboutMentorRoute,
  AuthIndexRoute: AuthIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
